name: Slither Analysis
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # 推送到 Code Scanning 需要此权限
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.4.1
        with:
          sarif: results.sarif
          fail-on: none        # 测试场景修改为 none ，正式场景为 false